parameters:
  - name: branch
    displayName: branch
    type: string
    default: 'testbranch'

variables:
  - name: branch_name
    value: ${{ parameters.branch }}

resources:
  repositories:
  - repository: pre-commit-hooks
    type: github
    ref: 'refs/heads/$(branch_name)'
    name: thomast1906/tamops-pre-commit-hooks
    endpoint: 'thomast1906'

stages:
  - stage: stage1
    jobs:
    - job: stage1job
      steps:
        - checkout: self
        - checkout: pre-commit-hooks

